### PR TITLE
Added generators with updated data files

### PR DESCRIPTION
**Pull request by kyordhel**
Please check data integrity before merge. I didn't find any error but still may have missed some one.

### CODE REVIEW

**Comment by moriarty** [comment]
windows? o.O

**Comment by moriarty** [comment]
I tested this on Windows 10, in VMware Fusion.

It seems okay, just one remark:

Press Esc to quit, c to clear, Enter to generate batch.
Choose question category: 1 [p]redefined, 2 [a]rena, 3 c[r]owd, 4 [o]bject
1
```
==================================
Question

question
        Q: What invented Grace Hopper?
        A: Grace Hopper invented the first compiler.

===================================
```

Should be:

```
        Q: What did Grace Hopper Invent?
```

**Comment by moriarty** [comment]
The xml file isn't in this pull request but I suggest:

```diff
4c4
<               <q>In which city are we in?</q>
---
>               <q>What city are we in?</q>
```

or ( double "in" in question- either can be removed )

```diff
4c4
<               <q>In which city are we in?</q>
---
>               <q>In which city are we?</q>
```

```diff
20c20
<               <a>Hillary Clinton was the popular vote in the US</a>
---
>               <a>Hillary Clinton won the popular vote.</a>
35c35
<               <a>Domestic Service Platform League.</a>
---
>               <a>Domestic Standard Platform League.</a>
40c40
<               <a>Service Robotics Standford Platform League.</a>
---
>               <a>Social Standard Platform League.</a>
49c49
<               <q>Nagoya has one of the largest train stations in the world how large is it?</q>
---
>               <q>Nagoya has one of the largest train stations in the world: how large is it?</q>
69c69
<               <q>What invented Grace Hopper?</q>
---
>               <q>What did Grace Hopper invent?</q>
```

**Comment by moriarty** [comment]
GitHub doesn't allow uploading *.xml* files so just I added *.txt*
[Questions.xml.txt](https://github.com/RoboCupAtHome/Nagoya2017/files/1174210/Questions.xml.txt)

**Comment by kyordhel** [comment]
I changed some questions/answers to make them clearer.  We can discuss it tomorrow morning, that's almost trivial to patch.

**Pull request merged**
